package payback

import (
	"errors"
	"fmt"
	"math/big"
	"strings"
	"sync"
	"time"

	"github.com/Fantom-foundation/go-opera/inter/iblockproc"
	"github.com/Fantom-foundation/go-opera/opera"
	sfcContract "github.com/Fantom-foundation/go-opera/opera/contracts/sfc"
	"github.com/Fantom-foundation/go-opera/payback/contract/paybackProxy"
	sfcBinding "github.com/Fantom-foundation/go-opera/payback/contract/sfc"
	"github.com/Fantom-foundation/lachesis-base/inter/idx"
	"github.com/ethereum/go-ethereum/log"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/core/vm"
)

const (
	paybackStaticCallGas = 100_000

	maxPaybackEntries = 50_000

	abiEncodedUint256Len = 32
)

type TxType string

const (
	TxTypeStake   TxType = "stake"
	TxTypeUnstake TxType = "unstake"
	TxTypeNone    TxType = "none"
)

type TxInfo struct {
	Tx      *types.Transaction
	Receipt *types.Receipt
	Type    TxType
}

type BlockInfo struct {
	BlockNumber   uint64
	Txs           []TxInfo
	BaseFeePerGas *big.Int
}

type StakeInfo struct {
	Amount    *big.Int
	Timestamp time.Time
}

type EpochStakes struct {
	StakesByAddress map[common.Address][]StakeInfo
}

// blockContext holds values that remain constant for the duration of a single
// block's processing, avoiding repeated store lookups per transaction.
type blockContext struct {
	epoch     idx.Epoch
	rules     opera.Rules
	blockTime time.Time

	baseRewardPerSecond *big.Int
	totalStakeSFC       *big.Int
	totalStakeQuota     *big.Int
}

type PaybackCache struct {
	mu sync.RWMutex

	// PaybackUsedMap contains last quota used
	PaybackUsedMap map[common.Address]*big.Int

	// StakesMap contains stakes and unstakes
	StakesMap map[idx.Epoch]*EpochStakes

	// ABI to get names of called methods
	contractABI *abi.ABI

	// sfcABI is used for baseRewardPerSecond calls to the SFC contract.
	sfcABI abi.ABI

	store Store

	contractAddress common.Address

	// maxAddresses is the maximum number of entries allowed in PaybackUsedMap and
	// StakesMap per epoch. Zero means use the package-level maxPaybackEntries default.
	// When the limit is reached, new addresses are silently dropped.
	maxAddresses uint64

	// inBlockProcessing guards epoch cleanup to prevent mid-block resets.
	inBlockProcessing bool

	// lastCleanedEpoch tracks the most recent epoch for which cleanup ran,
	// preventing redundant cleanup within the same epoch.
	lastCleanedEpoch idx.Epoch

	blkCtx *blockContext
}

// PrepareForBlock caches per-block constants so they are not re-fetched per
// transaction. Must be called before processing any transactions in a block.
// Epoch cleanup runs here (before inBlockProcessing is set) so that
// PaybackUsedMap is reset at epoch boundaries.
func (pc *PaybackCache) PrepareForBlock(epoch idx.Epoch, rules opera.Rules, blockTime time.Time) {
	pc.mu.Lock()
	defer pc.mu.Unlock()

	if epoch > pc.lastCleanedEpoch {
		pc.cleanupOldEpochsLocked(epoch)
		pc.lastCleanedEpoch = epoch
	}

	pc.blkCtx = &blockContext{
		epoch:     epoch,
		rules:     rules,
		blockTime: blockTime,
	}
	pc.inBlockProcessing = true
}

// FinishBlock marks the end of block processing, allowing epoch cleanup.
func (pc *PaybackCache) FinishBlock() {
	pc.mu.Lock()
	defer pc.mu.Unlock()
	pc.inBlockProcessing = false
	pc.blkCtx = nil
}

func (pc *PaybackCache) AddTransaction(tx *types.Transaction, receipt *types.Receipt) error {
	if receipt.Status == types.ReceiptStatusSuccessful {
		if pc.store == nil {
			return nil
		}

		pc.mu.Lock()
		defer pc.mu.Unlock()

		epoch := pc.getEpochLocked()
		txtype := getTxType(tx, *pc.contractABI)
		if txtype == TxTypeStake {
			blockTime := pc.getBlockTimeLocked()

			if pc.StakesMap[epoch] == nil {
				pc.StakesMap[epoch] = &EpochStakes{
					StakesByAddress: make(map[common.Address][]StakeInfo),
				}
			}

			// tx.From() relies on go-vinu's fork which caches the sender
			// recovered during signature verification. For internal txs the
			// sender is set explicitly by internaltx package.
			sender := tx.From()
			if sender == (common.Address{}) {
				return nil
			}

			if uint64(len(pc.StakesMap[epoch].StakesByAddress)) >= pc.effectiveMaxAddresses() {
				if _, exists := pc.StakesMap[epoch].StakesByAddress[sender]; !exists {
					log.Warn("StakesMap at capacity, ignoring new address", "address", sender)
					return nil
				}
			}

			stakes := pc.StakesMap[epoch].StakesByAddress[sender]
			stakes = append(stakes, StakeInfo{
				Amount:    new(big.Int).Set(tx.Value()),
				Timestamp: blockTime,
			})
			pc.StakesMap[epoch].StakesByAddress[sender] = stakes
		}

		if receipt.FeeRefund != nil && receipt.FeeRefund.Sign() > 0 {
			sender := tx.From()
			if sender == (common.Address{}) {
				return nil
			}

			// Sanity check: FeeRefund must not exceed the transaction fee.
			// This is always true when receipts are locally generated by
			// refundGas (which caps at min(fee, quota)), but guards against
			// future code paths that might construct receipts from external data.
			txFee := new(big.Int).Mul(new(big.Int).SetUint64(receipt.GasUsed), tx.GasPrice())
			feeRefund := receipt.FeeRefund
			if feeRefund.Cmp(txFee) > 0 {
				log.Error("FeeRefund exceeds tx fee, capping", "txHash", tx.Hash(), "feeRefund", feeRefund, "txFee", txFee)
				feeRefund = txFee
			}

			if uint64(len(pc.PaybackUsedMap)) >= pc.effectiveMaxAddresses() {
				if _, exists := pc.PaybackUsedMap[sender]; !exists {
					log.Warn("PaybackUsedMap at capacity, ignoring new address", "address", sender)
					return nil
				}
			}

			if _, ok := pc.PaybackUsedMap[sender]; !ok {
				pc.PaybackUsedMap[sender] = big.NewInt(0)
			}
			pc.PaybackUsedMap[sender].Add(pc.PaybackUsedMap[sender], feeRefund)
		}

	}
	return nil
}

// effectiveMaxAddresses returns the capacity limit for address-keyed maps.
// Falls back to maxPaybackEntries when the field is zero (e.g. in tests that
// construct PaybackCache directly rather than via NewPaybackCache).
func (pc *PaybackCache) effectiveMaxAddresses() uint64 {
	if pc.maxAddresses == 0 {
		return maxPaybackEntries
	}
	return pc.maxAddresses
}

func (pc *PaybackCache) getQuotaUsedLocked(address common.Address) *big.Int {
	if _, ok := pc.PaybackUsedMap[address]; ok {
		return new(big.Int).Set(pc.PaybackUsedMap[address])
	}
	return big.NewInt(0)
}

func NewPaybackCache(store Store, maxAddresses uint64) (*PaybackCache, error) {
	pc := PaybackCache{
		PaybackUsedMap: make(map[common.Address]*big.Int),
		StakesMap:      make(map[idx.Epoch]*EpochStakes),
		store:          store,
		maxAddresses:   maxAddresses,
	}

	if store.GetRules().Upgrades.Podgorica {
		pc.contractAddress = store.GetRules().Economy.QuotaCacheAddress
		log.Info("NewPaybackCache: PaybackCacheAddress is set", "address", pc.contractAddress.String())
	} else {
		rules := store.GetRules()
		log.Info("NewPaybackCache: Podgorica not active", "networkID", rules.NetworkID, "podgorica", rules.Upgrades.Podgorica)
	}

	abiQuotaProxy, err := abi.JSON(strings.NewReader(paybackProxy.QuotaProxyABI))
	if err != nil {
		return nil, fmt.Errorf("failed to parse payback proxy ABI: %w", err)
	}
	pc.contractABI = &abiQuotaProxy

	sfcABI, err := abi.JSON(strings.NewReader(sfcBinding.ContractABI))
	if err != nil {
		return nil, fmt.Errorf("failed to parse SFC ABI: %w", err)
	}
	pc.sfcABI = sfcABI

	return &pc, nil
}

// SetContractABI sets the ABI used for transaction type identification.
// Must be called before the cache is used for block processing.
func (pc *PaybackCache) SetContractABI(a *abi.ABI) {
	pc.mu.Lock()
	defer pc.mu.Unlock()
	pc.contractABI = a
}

// String returns a summary without per-address data to avoid leaking
// financial state in logs.
func (pc *PaybackCache) String() string {
	pc.mu.RLock()
	defer pc.mu.RUnlock()
	stakeEpochs := len(pc.StakesMap)
	return fmt.Sprintf("PaybackCache{addresses=%d, stakeEpochs=%d}", len(pc.PaybackUsedMap), stakeEpochs)
}

func getTxType(tx *types.Transaction, abi abi.ABI) TxType {
	if tx.Data() != nil && len(tx.Data()) >= 4 {
		if method, err := abi.MethodById(tx.Data()[:4]); err == nil {
			if method.Name == "stake" {
				return TxTypeStake
			}

			if method.Name == "unstake" {
				return TxTypeUnstake
			}
		}
	}
	return TxTypeNone
}

// GetAvailablePaybackByAddress calculates the available quota for a given address.
// getPaybackDataLocked reads epoch, quota, and duration under the lock.
// Returns ok=false if the epoch is invalid.
func (pc *PaybackCache) getPaybackDataLocked(address common.Address) (currentEpoch idx.Epoch, quotaUsed *big.Int, fullDuration int64, ok bool) {
	pc.mu.Lock()
	defer pc.mu.Unlock()

	currentEpoch = pc.getEpochLocked()
	if currentEpoch < 1 {
		log.Warn("GetAvailablePaybackByAddress: currentEpoch is 0, cannot compute payback")
		return 0, nil, 0, false
	}
	prevEpoch := currentEpoch - 1

	if pc.StakesMap[currentEpoch] == nil {
		pc.StakesMap[currentEpoch] = &EpochStakes{
			StakesByAddress: make(map[common.Address][]StakeInfo),
		}
	}

	quotaUsed = pc.getQuotaUsedLocked(address)
	prevEpochState := pc.store.GetHistoryEpochState(prevEpoch)
	fullDuration = pc.calculateFullDurationLocked(address, currentEpoch, prevEpochState)
	return currentEpoch, quotaUsed, fullDuration, true
}

// The evm parameter is passed directly to avoid storing a mutable pointer on the cache.
//
// Must be called during block processing (inBlockProcessing invariant). The epoch
// and PaybackUsedMap are stable during this period, so the single lock section
// below is safe and free from TOCTOU races.
func (pc *PaybackCache) GetAvailablePaybackByAddress(address common.Address, evm *vm.EVM) *big.Int {
	payback := big.NewInt(0)

	pc.mu.RLock()
	processing := pc.inBlockProcessing
	pc.mu.RUnlock()
	if !processing {
		log.Crit("GetAvailablePaybackByAddress called outside block processing")
		return payback
	}

	if address == (common.Address{}) {
		return payback
	}

	contractAddr, err := pc.resolveContractAddress()
	if err != nil {
		log.Warn("GetAvailablePaybackByAddress:", "error", err)
		return payback
	}

	if contractAddr == (common.Address{}) {
		return payback
	}

	addressTotalStake, err := pc.getAddressTotalStake(address, evm, contractAddr)
	if err != nil {
		log.Warn("GetAvailablePaybackByAddress:", "error", err)
		return payback
	}

	minStake, err := pc.getMinStake(address, evm, contractAddr)
	if err != nil {
		log.Warn("GetAvailablePaybackByAddress:", "error", err)
		return payback
	}

	if addressTotalStake.Cmp(minStake) < 0 {
		return payback
	}

	_, quotaUsed, fullDuration, ok := pc.getPaybackDataLocked(address)
	if !ok {
		return payback
	}

	baseRewardPerSecond, sumTotalStake, err := pc.calculateStakeDetails(address, evm, contractAddr)
	if err != nil {
		log.Warn("GetAvailablePaybackByAddress:", "error", err)
		return payback
	}

	log.Debug("GetAvailablePaybackByAddress:", "baseRewardPerSecond", baseRewardPerSecond)
	log.Debug("GetAvailablePaybackByAddress:", "sumTotalStake", sumTotalStake)

	multiplier := big.NewInt(1e10)
	addressTotalStakeMultiplied := new(big.Int).Mul(addressTotalStake, multiplier)
	log.Debug("GetAvailablePaybackByAddress:", "addressTotalStakeMultiplied", addressTotalStakeMultiplied)

	sliceOfBaseRewardPerSecondPercent := new(big.Int).Div(addressTotalStakeMultiplied, sumTotalStake)
	log.Debug("GetAvailablePaybackByAddress:", "sliceOfBaseRewardPerSecondPercent * multiplier(1e10)", sliceOfBaseRewardPerSecondPercent)
	log.Debug("GetAvailablePaybackByAddress:", "fullDuration", fullDuration)

	paybackSum := pc.calculatePayback(multiplier, baseRewardPerSecond, sliceOfBaseRewardPerSecondPercent, fullDuration)

	paybackSum = new(big.Int).Sub(paybackSum, quotaUsed)
	log.Debug("GetAvailablePaybackByAddress:", "paybackSum after subtracting used payback", paybackSum)

	if paybackSum.Sign() < 0 {
		log.Warn("GetAvailablePaybackByAddress: paybackSum is negative", "paybackSum", paybackSum)
		return big.NewInt(0)
	}

	return paybackSum
}

// calculatePayback calculates the available quota based on the base reward per second, the percentage of total stake, and the full duration.
func (pc *PaybackCache) calculatePayback(multiplier, baseRewardPerSecond, sliceOfBaseRewardPerSecondPercent *big.Int, fullDuration int64) *big.Int {
	sliceOfBaseRewardPerSecondValueMultiplied := new(big.Int).Mul(baseRewardPerSecond, sliceOfBaseRewardPerSecondPercent)
	sliceOfBaseRewardPerSecondValue := new(big.Int).Div(sliceOfBaseRewardPerSecondValueMultiplied, multiplier)

	paybackSum := big.NewInt(0)
	paybackSum = paybackSum.Mul(sliceOfBaseRewardPerSecondValue, big.NewInt(fullDuration))

	return paybackSum
}

// resolveContractAddress returns the current contract address, updating it if
// rules have changed. Uses RLock for the common fast path and only upgrades
// to a write lock when the cached address needs updating.
func (pc *PaybackCache) resolveContractAddress() (common.Address, error) {
	if pc.store == nil {
		return common.Address{}, errors.New("store is nil")
	}

	pc.mu.RLock()
	var rules opera.Rules
	if pc.blkCtx != nil {
		rules = pc.blkCtx.rules
	} else {
		rules = pc.store.GetRules()
	}

	if rules.NetworkID == 0 {
		pc.mu.RUnlock()
		return common.Address{}, errors.New("rules are empty")
	}

	if !rules.Upgrades.Podgorica {
		pc.mu.RUnlock()
		return common.Address{}, nil
	}

	newContractAddress := rules.Economy.QuotaCacheAddress
	if pc.contractAddress == newContractAddress {
		addr := pc.contractAddress
		pc.mu.RUnlock()
		return addr, nil
	}
	pc.mu.RUnlock()

	pc.mu.Lock()
	defer pc.mu.Unlock()

	if pc.blkCtx != nil {
		rules = pc.blkCtx.rules
	} else {
		rules = pc.store.GetRules()
	}
	newContractAddress = rules.Economy.QuotaCacheAddress
	if pc.contractAddress != newContractAddress {
		pc.contractAddress = newContractAddress
		log.Debug("resolveContractAddress: QuotaCacheAddress updated", "address", newContractAddress.String())
	}

	return pc.contractAddress, nil
}

// calculateStakeDetails computes the total stakes and base reward for an address.
// Block-invariant values (baseRewardPerSecond, totalStakeSFC, totalStakeQuota)
// are cached in the blockContext after the first EVM call within a block.
func (pc *PaybackCache) calculateStakeDetails(address common.Address, evm *vm.EVM, contractAddr common.Address) (*big.Int, *big.Int, error) {
	pc.mu.RLock()
	if pc.blkCtx != nil && pc.blkCtx.baseRewardPerSecond != nil {
		brps := new(big.Int).Set(pc.blkCtx.baseRewardPerSecond)
		sumTotalStake := new(big.Int).Add(
			new(big.Int).Set(pc.blkCtx.totalStakeSFC),
			new(big.Int).Set(pc.blkCtx.totalStakeQuota),
		)
		pc.mu.RUnlock()
		if sumTotalStake.Sign() == 0 {
			log.Warn("calculateStakeDetails", "sumTotalStake", "is zero")
			return nil, nil, errors.New("sum of total stakes is zero")
		}
		return brps, sumTotalStake, nil
	}
	pc.mu.RUnlock()

	baseRewardPerSecond, err := pc.getBaseRewardPerSecond(address, evm)
	if err != nil {
		log.Warn("calculateStakeDetails:", "error", err)
		return nil, nil, err
	}

	totalStakeSFC, err := pc.getTotalStake(address, sfcContract.ContractAddress, evm)
	if err != nil {
		log.Warn("calculateStakeDetails:", "error", err)
		return nil, nil, err
	}

	totalStakeQuota, err := pc.getTotalStake(address, contractAddr, evm)
	if err != nil {
		log.Warn("calculateStakeDetails:", "error", err)
		return nil, nil, err
	}

	func() {
		pc.mu.Lock()
		defer pc.mu.Unlock()
		if pc.blkCtx != nil && pc.blkCtx.baseRewardPerSecond == nil {
			pc.blkCtx.baseRewardPerSecond = new(big.Int).Set(baseRewardPerSecond)
			pc.blkCtx.totalStakeSFC = new(big.Int).Set(totalStakeSFC)
			pc.blkCtx.totalStakeQuota = new(big.Int).Set(totalStakeQuota)
		}
	}()

	sumTotalStake := new(big.Int).Add(totalStakeSFC, totalStakeQuota)
	if sumTotalStake.Sign() == 0 {
		log.Warn("calculateStakeDetails", "sumTotalStake", "is zero")
		return nil, nil, errors.New("sum of total stakes is zero")
	}

	return baseRewardPerSecond, sumTotalStake, nil
}

// calculateFullDurationLocked calculates the effective duration of stakes for
// quota calculations. Caller must hold pc.mu.
func (pc *PaybackCache) calculateFullDurationLocked(address common.Address, currentEpoch idx.Epoch, prevEpochState *iblockproc.EpochState) int64 {
	// Caller (GetAvailablePaybackByAddress) guarantees currentEpoch >= 1, so this is safe from underflow.
	prevEpoch := currentEpoch - 1
	sumCurrent, sumPrev := pc.getSumStakeByAddressSplitLocked(address, currentEpoch, prevEpoch)

	var fullDuration int64

	if sumCurrent.Sign() > 0 && sumPrev.Sign() == 0 {
		lastBlockTime := pc.getBlockTimeLocked()
		stakes := pc.getStakesForEpochLocked(currentEpoch, address)

		if len(stakes) == 0 {
			log.Warn("calculateFullDurationLocked: no stakes found for current epoch despite non-zero sum")
			return 0
		}
		lastTimeStake := stakes[len(stakes)-1].Timestamp
		dur := lastBlockTime.Sub(lastTimeStake)
		fullDuration = int64(dur / 1e9)
		if fullDuration < 0 {
			fullDuration = 0
		}
		return fullDuration
	}

	if prevEpochState == nil {
		log.Warn("calculateFullDurationLocked: epoch state not found for prevEpoch", "prevEpoch", prevEpoch)
		return 0
	}
	durationPrevEpochBySec := prevEpochState.Duration() / 1e9
	// Clamp to a reasonable maximum epoch duration (1 year).
	// Genesis epoch (PrevEpochStart == 0) returns the UNIX timestamp as Duration(),
	// which is ~54 years and would inflate quota by orders of magnitude.
	const maxReasonableEpochSec = 365 * 24 * 3600
	if durationPrevEpochBySec > maxReasonableEpochSec {
		log.Warn("calculateFullDurationLocked: epoch duration exceeds 1 year, clamping to zero",
			"prevEpoch", prevEpoch, "durationSec", durationPrevEpochBySec)
		return 0
	}
	fullDuration = int64(durationPrevEpochBySec)
	if fullDuration < 0 {
		fullDuration = 0
	}

	return fullDuration
}

func (pc *PaybackCache) getAddressTotalStake(address common.Address, evm *vm.EVM, contractAddr common.Address) (*big.Int, error) {
	sender := vm.AccountRef(common.Address{})
	packedData, err := pc.contractABI.Pack("getStake", address)
	if err != nil {
		return big.NewInt(0), err
	}

	result, _, vmerr := evm.StaticCall(sender, contractAddr, packedData, paybackStaticCallGas)
	if vmerr != nil {
		return big.NewInt(0), vmerr
	}

	return decodeUint256(result)
}

func (pc *PaybackCache) getMinStake(address common.Address, evm *vm.EVM, contractAddr common.Address) (*big.Int, error) {
	sender := vm.AccountRef(common.Address{})
	packedData, err := pc.contractABI.Pack("minStake")
	if err != nil {
		return big.NewInt(0), err
	}

	result, _, vmerr := evm.StaticCall(sender, contractAddr, packedData, paybackStaticCallGas)
	if vmerr != nil {
		return big.NewInt(0), vmerr
	}

	return decodeUint256(result)
}

func (pc *PaybackCache) GetStore() Store {
	return pc.store
}

func (pc *PaybackCache) getBaseRewardPerSecond(address common.Address, evm *vm.EVM) (*big.Int, error) {
	sender := vm.AccountRef(common.Address{})
	packedData, err := pc.sfcABI.Pack("baseRewardPerSecond")
	if err != nil {
		return big.NewInt(0), err
	}

	result, _, vmerr := evm.StaticCall(sender, sfcContract.ContractAddress, packedData, paybackStaticCallGas)
	if vmerr != nil {
		return big.NewInt(0), vmerr
	}

	return decodeUint256(result)
}

func (pc *PaybackCache) getTotalStake(address common.Address, contractAddress common.Address, evm *vm.EVM) (*big.Int, error) {
	sender := vm.AccountRef(common.Address{})

	var (
		packedData []byte
		err        error
	)

	if contractAddress == sfcContract.ContractAddress {
		packedData, err = pc.sfcABI.Pack("totalStake")
	} else {
		packedData, err = pc.contractABI.Pack("totalStake")
	}
	if err != nil {
		return big.NewInt(0), err
	}

	result, _, vmerr := evm.StaticCall(sender, contractAddress, packedData, paybackStaticCallGas)
	if vmerr != nil {
		return big.NewInt(0), vmerr
	}

	return decodeUint256(result)
}

// decodeUint256 validates that result is exactly 32 bytes, decodes as a uint256,
// and rejects values above maxReasonableUint256 to prevent CPU spikes from
// pathological proxy contract returns.
func decodeUint256(data []byte) (*big.Int, error) {
	if len(data) != abiEncodedUint256Len {
		return big.NewInt(0), fmt.Errorf("expected %d bytes of return data, got %d", abiEncodedUint256Len, len(data))
	}
	v := new(big.Int).SetBytes(data)
	if v.BitLen() > 128 {
		return big.NewInt(0), fmt.Errorf("decodeUint256: value exceeds 128-bit cap, bitLen=%d", v.BitLen())
	}
	return v, nil
}

// getStakesForEpochLocked requires pc.mu to be held by the caller.
func (pc *PaybackCache) getStakesForEpochLocked(epoch idx.Epoch, address common.Address) []StakeInfo {
	if epochStakes, ok := pc.StakesMap[epoch]; ok {
		if stakes, ok := epochStakes.StakesByAddress[address]; ok {
			dst := make([]StakeInfo, len(stakes))
			copy(dst, stakes)
			return dst
		}
	}
	return nil
}

// getSumStakeByAddressSplitLocked computes the stake sums for the current and
// previous epochs in a single pass. Caller must hold pc.mu.
func (pc *PaybackCache) getSumStakeByAddressSplitLocked(address common.Address, currentEpoch, prevEpoch idx.Epoch) (current, prev *big.Int) {
	current = big.NewInt(0)
	prev = big.NewInt(0)

	for _, epoch := range []idx.Epoch{prevEpoch, currentEpoch} {
		if epochStakes, ok := pc.StakesMap[epoch]; ok {
			if stakes, ok := epochStakes.StakesByAddress[address]; ok {
				target := prev
				if epoch == currentEpoch {
					target = current
				}
				for _, stake := range stakes {
					target.Add(target, stake.Amount)
				}
			}
		}
	}

	return current, prev
}

// cleanupOldEpochsLocked removes epoch data older than 2 epochs and resets the
// cleanupOldEpochsLocked prunes stale epoch data from StakesMap and resets
// PaybackUsedMap. Quotas are per-epoch, so used amounts must be zeroed when
// the epoch advances. Called from PrepareForBlock before inBlockProcessing
// is set, ensuring cleanup happens exactly once per epoch transition.
// Caller must hold pc.mu write lock.
func (pc *PaybackCache) cleanupOldEpochsLocked(currentEpoch idx.Epoch) {
	if currentEpoch <= 2 {
		pc.PaybackUsedMap = make(map[common.Address]*big.Int)
		return
	}
	cutoffEpoch := currentEpoch - 2

	for epoch := range pc.StakesMap {
		if epoch < cutoffEpoch {
			delete(pc.StakesMap, epoch)
		}
	}

	pc.PaybackUsedMap = make(map[common.Address]*big.Int)
}

// getEpochLocked returns the current epoch, preferring the cached block context.
// Caller must hold pc.mu (read or write).
func (pc *PaybackCache) getEpochLocked() idx.Epoch {
	if pc.blkCtx != nil {
		return pc.blkCtx.epoch
	}
	return pc.store.GetCurrentEpoch()
}

// getBlockTimeLocked returns the block time from block context if available.
// Caller must hold pc.mu.
func (pc *PaybackCache) getBlockTimeLocked() time.Time {
	if pc.blkCtx != nil {
		return pc.blkCtx.blockTime
	}
	block := pc.store.GetBlock(idx.Block(pc.store.GetLatestBlockIndex()))
	if block == nil {
		return time.Time{}
	}
	return block.Time.Time()
}
